### ISSUE TITLE
Uncaught Exception: RangeError: Index out of range

### ISSUE THREAD

**Issue by bastelbert** [coolchip/node-red-contrib-luxtronik2#1]
Hi, 

first of all thanks for your great work!
Unfortunately I am running into an error using node-red-contrib-luxtronik2.

node-red: 0.19.5
node-red-contrib-luxtronik2: 0.3.0
Novelan LD5 heatpump.
Luxtronik2 firmware: V2.79

Error message: 
Dec 28 12:41:05 loxberry Node-RED[15443]: 28 Dec 12:41:05 - [red] Uncaught Exception:
Dec 28 12:41:05 loxberry Node-RED[15443]: 28 Dec 12:41:05 - RangeError: Index out of range
Dec 28 12:41:05 loxberry Node-RED[15443]:     at checkOffset (buffer.js:977:11)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at Uint8Array.Buffer.readInt32BE (buffer.js:1142:5)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at Luxtronik.<anonymous> (/root/.node-red/node_modules/luxtronik2/luxtronik.js:410:37)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at emitOne (events.js:116:13)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at Socket.emit (events.js:211:7)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at addChunk (_stream_readable.js:263:12)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at readableAddChunk (_stream_readable.js:250:11)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at Socket.Readable.push (_stream_readable.js:208:10)
Dec 28 12:41:05 loxberry Node-RED[15443]:     at TCP.onread (net.js:601:20)
Dec 28 12:41:05 loxberry systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
Dec 28 12:41:05 loxberry systemd[1]: nodered.service: Unit entered failed state.
Dec 28 12:41:05 loxberry systemd[1]: nodered.service: Failed with result 'exit-code'.
Dec 28 12:41:05 loxberry systemd[1]: nodered.service: Service hold-off time over, scheduling restart.

Maybe it's because I changed the default Luxtronik webserver pw from 888888 to another one?

**Comment by coolchip** [comment]
Hey, thank you very much for reporting.
I don't think the password is needed for access at all. So I don't think, this is a problem. Or did you mean the ethernet port number?
It seems, as if your luxtronik respond an unexpected data stream. I also don't know the Novelan LD5. But this shouldn't matter if you have a Luxtronik2.
Witch node.js version you are running `node --version`?

**Comment by coolchip** [comment]
No response, so I will close this.
