### ISSUE TITLE
Warmwasser Sollwert

### ISSUE THREAD

**Issue by PabloEscoba84** [coolchip/node-red-contrib-luxtronik2#11]
Hallo,

mir ist aufgefallen, dass wenn ich beim Ausgabebaustein den Parameter "Warmwater Target" auswähle, der Wert nicht in den Eintrag den Parameter "payload.parameters.temperature_hot_water_target" geschrieben wird, sondern in "payload.parameters.warmwater_temperature".

Gibt es irgendwo eine Anleitung wie ich ohne die Parameterauswahl des Bausteins selber das Objekt definieren kann welches ich beschreiben möchte. Also in meinem Fall "payload.parameters.temperature_hot_water_target" die Sollwertvorgabe.

Edit:

Habe den Eintrag in der luxtronik,js geändert:

![Unbenannt](https://user-images.githubusercontent.com/80603215/204134423-087acf5a-10a0-4025-8b3b-d1891f3c8e8b.PNG)

Hier stand zuvor eine "2" drin.

**Comment by coolchip** [comment]
Hallo,
glaube die Stelle wurde mal von jemandem geändert. Ich weiß leider nicht, warum es bei der Pumpe unterschiedliche Parameter dafür gibt. Ich weiß nicht, ob dir das weiter hilft. Aber du kannst im Prinzip die ganzen Parameter frei angeben. Sieht dann so aus:
```json
[
    {
        "id": "8499196.93debe8",
        "type": "inject",
        "z": "7971f5eb.adf7ec",
        "name": "",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": "",
        "topic": "",
        "payload": "3",
        "payloadType": "num",
        "x": 110,
        "y": 1020,
        "wires": [
            [
                "603eade3.c9adc4"
            ]
        ]
    },
    {
        "id": "603eade3.c9adc4",
        "type": "change",
        "z": "7971f5eb.adf7ec",
        "name": "return_temperature_hysteresis",
        "rules": [
            {
                "t": "set",
                "p": "parameter",
                "pt": "msg",
                "to": "return_temperature_hysteresis",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 350,
        "y": 980,
        "wires": [
            [
                "c6ce4676.ea18c8"
            ]
        ]
    },
    {
        "id": "c6ce4676.ea18c8",
        "type": "luxtronik2 write",
        "z": "7971f5eb.adf7ec",
        "name": "",
        "host": "192.168.178.22",
        "port": "8888",
        "parameter": "",
        "x": 700,
        "y": 900,
        "wires": [
            [
                "543d18a8.36d8f8"
            ]
        ]
    },
    {
        "id": "543d18a8.36d8f8",
        "type": "debug",
        "z": "7971f5eb.adf7ec",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 890,
        "y": 900,
        "wires": []
    }
]
```

Wenn nicht, können wir den alten Parameter aber auch wieder einbauen.

**Comment by mojo2012** [comment]
Der Unterschied ist, dass das "Warmwater target" das Setting "WP-Deckung" setzt, nicht die "Wunschtemperatur".
Ich musste auch gerade mit `msg.parameter = 'temperature_hot_water_target'` den korrekten parameter setzen.

**Comment by peterdermeter** [comment]
Hallo, hab die Node gerade zum ersten mal verwendet, um bei PV-Überschuss die Warmwasser-Wunschtemperatur hochzusetzen. Leider wird mit dem Parameter "warmwater_target_temperature" wie oben geschrieben die "WP-Deckung" und nicht die "Wunschtemperatur" gesetzt. Gibt es eine Möglichkeit, dass ich die Wunschtemperatur setze?

**Comment by sofa74surfer** [comment]
Hallo @peterdermeter 
Bei mir steht immer noch die 2 im Code drin und dies ändert bei meiner Wärmepumpe mit Luxtronik 2.0 die Soll-Temperatur. 
```
        'warmwater_target_temperature': {
            setParameter: 2,
            setValue: utils.value2LuxtronikSetTemperatureValue(utils.limitRange(realValue, 30, 65))
```
Ändere ich den Wert von 56 auf 55, dann  ändert sich: 

Values temperature_hot_water_target (18) auf 56
Parameter warmwater_temperature (2) auf 56 

Der Parameter temperature_hot_water_target (105) bleibt unverändert. 

Für mich stimmt die '2'. 

temperature_hot_water_target gibt es sowohl als Value und auch als Parameter und das ist offenbar nicht das Gleiche.

**Comment by peterdermeter** [comment]
Hallo @sofa74surfer ,
vielen Dank für deine schnelle Antwort. Bei mir steht auch die 2 drin. Kann ich es bedenkenlos zu 105 ändern, sodass über die Ausgabe-Node über die Parameterangabe "warmwater_target_temperature" dann "temperature_hot_water_target" angesprochen wird?

**Comment by sofa74surfer** [comment]
Hallo @peterdermeter 
Wenn du den Parameter 105 ändern willst, warum nimmst du nicht einfach temperature_hot_water_target?
```
        'temperature_hot_water_target': {
            setParameter: 105,
            setValue: utils.value2LuxtronikSetTemperatureValue(realValue)
```
Damit du das im Node Red GUI auswählen kannst, müsstest du den Parameter einfach im [index.html](https://github.com/coolchip/node-red-contrib-luxtronik2/blob/master/index.html) hinzufügen. 

Ich habe einen [Pull Request](https://github.com/coolchip/node-red-contrib-luxtronik2/pull/15) erstellt, damit die fehlenden Parameter hinzukommen.

**Comment by coolchip** [comment]
Danke für die Hilfe. Werde in Kürze eine Version machen.
