### ISSUE TITLE
Parameter Password needed

### ISSUE THREAD

**Issue by Nexus1212** [coolchip/node-red-contrib-luxtronik2#12]
Hello,
my Novelan controll unit need a password to connect.

Error massage:
msg.payload : error
"Error: connect ECONNREFUSED 192.168.1.85:8888"

Software-Version:
V3.88.0

Solution:
Default pw is "999999".
Could you add the possibility to add a password parameter (like node-red-contrib-luxtronik2-ws)

Beste regard
Nexus

**Comment by coolchip** [comment]
I am afraid the new firmware does not work with this node. Maybe you can try to use port 8889. Maybe that will still work.

**Comment by Nexus1212** [comment]
Hi, the port 8889 is working!
