### ISSUE TITLE
It works 2 day's and now - msg.payload : error "Error: read ECONNRESET"

### ISSUE THREAD

**Issue by schorges** [coolchip/node-red-contrib-luxtronik2#13]
It work for 5,6  day's and now fail to load - msg.payload : error "Error: read ECONNRESET"

on goto browser to my headpump, i can see all infos via websocket,
i have no passwort.

restart of all dosen't help !!?

**Comment by mojo2012** [comment]
Same here. All of a sudden, I had to change the port to `8889` to make it work again.
It worked with `8888` before, I think.

**Comment by coolchip** [comment]
I think there is a change for the newer pumps. I still have the old one without WebSockets.
