### ISSUE TITLE
Write Error:           "Error: connect ETIMEDOUT 182.168.21.51:8888"

### ISSUE THREAD

**Issue by RedCross0815** [coolchip/node-red-contrib-luxtronik2#3]
Hi, i need a little help:

i can read data from the heatpump without any problems.

But when i try to write, i got the error: "Error: connect ETIMEDOUT 182.168.21.51:8888"

Its a Novelan LAD5 Heatpump. The Luxtronik module have the Version 2.81.
Do i have to change a parameter in the Heatpump to write into it? I just wanted to turn the "Heating operation" in automatic or off.

Many thanks

**Comment by coolchip** [comment]
That's currious. Perhaps they changend something. For example requiring a password. My version is v1.80.
