### ISSUE TITLE
Read error: "Error: heatpump busy"

### ISSUE THREAD

**Issue by saemmy** [coolchip/node-red-contrib-luxtronik2#4]
When trying to read data from my AlphaInnotec I get the follwing error in msg.payload:
"Error: heatpump busy"

But writing data with the same configuration is working. I also tried some older luxtronik nodes they also can read data. Any idea what could be wrong?

**Comment by coolchip** [comment]
Hello. Can you tell which version works correctly?

**Comment by josh-79** [comment]
I have the same Issue with my alpha innotec LWC80. The firmware version is  V1.80.

**Comment by coolchip** [comment]
I work with a LW71A. Previous with V1.80 now with V1.86. Both are working. In the next release I've added the status code to the error message. Perhaps this tells us anything about that problem. Please open an new issue if you see the state code.
