### ISSUE TITLE
Not able to update: payload.parameters.hotWaterOperationTimerTableWeek[0].on

### ISSUE THREAD

**Issue by trulsant** [coolchip/node-red-contrib-luxtronik2#9]
I am trying to control the time when hotWaterOperation is on or off. 
This is in the parameter hotWaterOperationTimerTableWeek[0].on or .off
These are populated with whatever I have entered on the Luxtronik controller manually. 

When trying to inject a value, the same was as it is working for e.g. payload.parameters.heating_curve_end_point, it don't work, no error messages, just is not updated.  

Are there any special way of "adressing" an array, other than using "hotWaterOperationTimerTableWeek[0].on" as parameter?

![image](https://user-images.githubusercontent.com/97249295/148429658-85e6600c-db38-4efe-bcf4-66090da6bd1a.png)

Truls

**Comment by coolchip** [comment]
Hello. Every parameter that you want to write into your heatpump has to be defined in the luxtronik.js implementation. Check this:
https://github.com/coolchip/luxtronik2/blob/9cd0f1e31c75438b6d952158d338ea4fd108bb7f/luxtronik.js#L590

Feel free to send me a pull request with all data you would like to send to your heatpump.

**Comment by Andy-W4n** [comment]
Was there already done a pull request? I would have the same use case and some other like temperature night reduction.

**Comment by coolchip** [comment]
Unfortunatelly not. I would need at least the matching IDs fir this.
You can slso look here:
https://github.com/Bouni/Luxtronik-2/blob/master/documentation.md#meaning-of-the-data

**Comment by Andy-W4n** [comment]
Is there a "trick" how to get the correct matching IDs?! 

I wolud need at least
- heating_curve_end_point for MK3
- heating_curve_parallel_offset for MK3
- if possible the parameter for "heating_curve_night_reduction" for heating_curve and MK3 which i also cannot find in the values

Do you know what i mean?!


"Nice to have" would be the array for hotWaterOperationTimerTableWeek[0].on, but perhaps that could be not as easy as setting only one value.

**Comment by coolchip** [comment]
The best way is to clone the depend none module https://github.com/coolchip/luxtronik2
There you can do and test the extensions you need. Do the changes and look at yout heatpump if the changes appears.

**Comment by waldbaer** [comment]
Even if there is no user-friendly abstraction yet for hot water operation timer table you could use the RAW write operations (see node docu with parameter `msg.raw_parameter` and `msg.payload`.
In the [luxtronik.js](https://github.com/coolchip/luxtronik2/blob/master/luxtronik.js) in added in the past several hints about the meaning of these timer table parameters.

for hotWaterOperationTimerWeek these parameter numbers are **406..415**
```
// hot water operation table 0: week.
'hotWaterOperationTimerTableWeek': utils.createTimerTable(heatpumpParameters, 406, 5, true), // 406..415
```

In my setup I am not modifying the hot water operation but the circulation pump timer. The timer settings (in seconds) might be identical.
```
// turn on circulation pump at 09:00
msg.raw_parameter = 507;
msg.payload=9*60*60;

// turn off circulation pump  at 22:00
msg.raw_parameter = 508;
msg.payload=22*60*60;
```

**Comment by coolchip** [comment]
Again, thank you very much @waldbaer for helping me answering questions.
